server:
  app_name: "GinAPI"
  port: "8080"
  environment: "development"
  read_timeout: "10s"
  write_timeout: "10s"
  max_body_size: 33554432  # 32MB

database:
  driver: "sqlite"
  dsn: "./data/app.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"

jwt:
  secret: "your-dev-secret-key"
  expiration_time: "1h"
  refresh_time: "24h"
  issuer: "gin-api-dev"

logging:
  level: "debug"
  format: "text"

security:
  rate_limit_rps: 10.0
  rate_limit_burst: 20
  auth_rate_limit: 5
  cors_enabled: true
  cors_origins: "*"
