server:
  app_name: "GinAPI"
  port: "8080"
  environment: "production"
  read_timeout: "30s"
  write_timeout: "30s"
  max_body_size: 10485760  # 10MB

database:
  driver: "postgres"
  dsn: "${DATABASE_URL}"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "30m"

jwt:
  secret: "${JWT_SECRET}"
  expiration_time: "15m"
  refresh_time: "7d"
  issuer: "gin-api"

logging:
  level: "info"
  format: "json"

security:
  rate_limit_rps: 5.0
  rate_limit_burst: 10
  auth_rate_limit: 3
  cors_enabled: true
  cors_origins: "https://yourdomain.com,https://www.yourdomain.com"
